project:
  type: website
  output-dir: docs

website:
  title: "AthenaAgent"
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
execute: 
  force: auto
